.TH MINISTOCKS 1
.SH NAME
ministocks \- minimalistic QT stock ticker for Linux
.SH DESCRIPTION
MiniStocks is a minimalistic stock ticker application built with Qt.
It displays stock prices, indices, and currency rates.
.SH AUTHOR
Maintained by Danial Maleki <danialmaleki.online@gmail.com>
.SH HOMEPAGE
https://github.com/Danial-maleki/MiniStocks
