.\"                                      Hey, EMACS: -*- nroff -*-
.TH MINISTOCKS 1 "2026-06-13" "0+git20200120-6" "MiniStocks Manual"
.SH NAME
ministocks \- minimalistic QT stock ticker for Linux
.SH SYNOPSIS
.B ministocks
[options]
.SH DESCRIPTION
\fBMiniStocks\fP is a minimalistic stock ticker application built with Qt.
It displays real-time stock prices, indices, and currency rates.
.SH OPTIONS
No command line options are currently supported.
.SH AUTHOR
Danial Maleki <danialmaleki.online@gmail.com>
.SH HOMEPAGE
https://github.com/Danial-maleki/MiniStocks
.SH COPYRIGHT
Copyright 2026 Danial Maleki
.br
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 as
published by the Free Software Foundation.
